package com.zxr.medicalaid;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER.
 */
public class User {

    private String uId;
    private Long id;
    private String userName;
    private String phoneNum;
    private String icon;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(String uId, Long id, String userName, String phoneNum, String icon) {
        this.uId = uId;
        this.id = id;
        this.userName = userName;
        this.phoneNum = phoneNum;
        this.icon = icon;
    }

    public String getUId() {
        return uId;
    }

    public void setUId(String uId) {
        this.uId = uId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPhoneNum() {
        return phoneNum;
    }

    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum;
    }

    public String getIcon() {
        return icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

}
